---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how bluexp volume caching works, what is volume caching, bluexp 
summary: Volume 快取可在遠端位置提供持續且可寫入的 Volume 。您可以使用 BlueXP 磁碟區快取來加速資料存取、或卸載大量存取磁碟區的流量。快取磁碟區是讀取密集工作負載的理想選擇、尤其是用戶端需要重複存取相同資料的地方。 
---
= 瞭解 BlueXP Volume 快取
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volume 快取是 ONTAP 9 軟體的一項功能、是一項遠端快取功能、可簡化檔案發佈、減少 WAN 延遲、讓資源更接近使用者和運算資源的位置、並降低 WAN 頻寬成本。Volume 快取可在遠端位置提供持續且可寫入的 Volume 。您可以使用 BlueXP 磁碟區快取來加速資料存取、或卸載大量存取磁碟區的流量。快取磁碟區是讀取密集工作負載的理想選擇、尤其是用戶端需要重複存取相同資料的地方。

有了 BlueXP Volume 快取、您就能擁有雲端的快取功能、特別是適用於 NetApp ONTAP 、 Cloud Volumes ONTAP 的 Amazon FSX 、以及內部部署的工作環境。

此服務也提供分公司存取公司資料集的權限。藉由提供需要經常從叢集中多個控制器存取的 _Hot data_ 資料、您可以提高提供給關鍵應用程式的效能。此外、透過快取全球多個地點的使用者本機熱資料、您可以同時存取集中式資料集、同時縮短存取熱資料時所收到的回應時間、藉此加強協同作業。



== 什麼是快取？

快取是位於主機和資料來源之間的暫存儲存位置。快取的目標是儲存經常存取的來源資料部分、使資料的處理速度比從來源擷取資料快。在讀取密集的環境中、快取最有幫助、因為在這種環境中、資料會多次存取、並由多部主機共用。快取系統比具有資料來源的系統快、這是透過更快的儲存系統和快取儲存空間鄰近主機來達成的。



== 使用 BlueXP Volume 快取的優點

BlueXP Volume 快取具有下列優點：

* 加速混合雲基礎架構的效能
* 將資料從一個雲端供應商快取至另一個雲端供應商、以移除雲端封閉環境
* 降低儲存成本
* 跨地理區域協同作業
* 在 BlueXP  中使用 NetApp 託管服務
* 更快因應瞬息萬變的 IT 環境
* 使用雲端託管的隨選或訂閱型 Volume 快取




== BlueXP Volume 快取的功能

BlueXP Volume 快取可讓您充分運用多項 NetApp 技術來達成下列目標：

* 將資料從一個雲端供應商快取至另一個雲端供應商。
* 檢視及編輯快取匯出原則。
* 調整現有快取的大小。
* 刪除快取。




== 成本

NetApp 並不收取使用 BlueXP Volume 快取服務的費用、但您必須向雲端供應商查詢適用的資料進出費用。



== 授權

BlueXP Volume 快取不需要特殊的 ONTAP 授權。



== BlueXP Volume 快取的運作方式

快取磁碟區是由來源磁碟區支援的稀疏填入磁碟區。快取磁碟區可以位於與來源磁碟區相同的叢集上、也可以位於不同的叢集上。

快取磁碟區可讓您存取來源磁碟區中的資料、而不需要將所有資料放在快取磁碟區中。只保留熱資料（工作中或最近使用的資料）、即可有效管理快取磁碟區中的資料儲存。

如果快取磁碟區包含用戶端要求的資料、 BlueXP 磁碟區快取會讀取要求。否則、 Volume 快取服務會從來源 Volume 要求資料、並在處理用戶端要求之前儲存資料。隨後的資料要求會直接從快取磁碟區傳送。當重複存取相同的資料時、這會改善效能、因為在第一次要求之後、資料就不再必須在網路上傳輸、或是從過載的系統中提供。
